# Generated by Django 2.1.5 on 2019-01-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcglacier', '0002_auto_20190107_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='area',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
