# Generated by Django 2.1.5 on 2019-01-08 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcglacier', '0003_auto_20190107_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('user', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcglacier.Sites')),
            ],
            options={
                'db_table': 'ratings',
                'managed': True,
            },
        ),
    ]
