# Generated by Django 2.1.4 on 2019-01-09 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcglacier', '0005_remove_ratings_site_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('info_date', models.DateTimeField(blank=True, null=True)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcglacier.Sites')),
            ],
            options={
                'db_table': 'information',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ratings',
            name='comment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
