# Generated by Django 2.1.5 on 2019-01-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcglacier', '0009_auto_20190111_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitesavgrating',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('park_id', models.IntegerField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=40, null=True)),
                ('fires', models.CharField(blank=True, max_length=5, null=True)),
                ('elevation', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('avgrating', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'SitesAvgRating',
                'managed': False,
            },
        ),
    ]
